apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-epoch-publisher
  namespace: atomix
spec:
  serviceName: "atomix-epoch-publisher"
  replicas: 1
  selector:
    matchLabels:
      app: atomix-epoch-publisher
  template:
    metadata:
      labels:
        app: atomix-epoch-publisher
    spec:
      containers:
      - name: epoch-publisher
        image: atomix-epoch-publisher:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: backend
          protocol: TCP
        - containerPort: 50052
          name: fast-network
          protocol: UDP
        env:
        - name: RUST_LOG
          value: "info"
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && epoch_publisher"]
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-config

---
apiVersion: v1
kind: Service
metadata:
  name: atomix-epoch-publisher
  namespace: atomix
spec:
  selector:
    app: atomix-epoch-publisher
  clusterIP: None
  ports:
    - name: backend
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: fast-network
      protocol: UDP
      port: 50052
      targetPort: 50052