---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-frontend
  namespace: atomix
  labels:
    app: atomix-frontend
spec:
  serviceName: "atomix-frontend"
  replicas: 1
  selector:
    matchLabels:
      app: atomix-frontend
  template:
    metadata:
      labels:
        app: atomix-frontend
    spec:
      containers:
      - name: frontend
        image: atomix-frontend:latest
        imagePullPolicy: IfNotPresent
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && frontend"]
        env:
          - name: RUST_BACKTRACE
            value: "1"
          - name: RUST_LOG
            value: "info"
        ports:
        - containerPort: 50057
          name: proto-server
          protocol: TCP
        - containerPort: 50058
          name: fast-network
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-config
---
apiVersion: v1
kind: Service
metadata:
  name: atomix-frontend
  namespace: atomix
spec:
  selector:
    app: atomix-frontend
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50057
      targetPort: 50057
      name: proto-server
    - protocol: UDP
      port: 50058
      targetPort: 50058
      name: fast-network