apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix-rangeserver
  namespace: atomix
spec:
  serviceName: "atomix-rangeserver"
  replicas: 1
  selector:
    matchLabels:
      app: atomix-rangeserver
  template:
    metadata:
      labels:
        app: atomix-rangeserver
    spec:
      containers:
      - name: rangeserver
        image: atomix-rangeserver:latest
        imagePullPolicy: IfNotPresent
        workingDir: /etc/atomix
        command: ["/bin/sh", "-c"]
        args: ["cat /etc/atomix/config.json && rangeserver"]
        env:
          - name: RUST_BACKTRACE
            value: "1"
          - name: RUST_LOG
            value: "info"
        ports:
        - containerPort: 50054
          name: proto-server
          protocol: TCP
        - containerPort: 50055
          name: fast-network
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /etc/atomix
      volumes:
      - name: config
        configMap:
          name: atomix-config
---
apiVersion: v1
kind: Service
metadata:
  name: atomix-rangeserver
  namespace: atomix
spec:
  selector:
    app: atomix-rangeserver
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
      name: proto-server
    - protocol: UDP
      port: 50055
      targetPort: 50055
      name: fast-network
